#!/bin/bash

: "${STATUS_VOLUME_PATH:?STATUS_VOLUME_PATH needs to be set and non-empty.}"

until [[ -f "${STATUS_VOLUME_PATH}/osm_bright.is_ready" ]]
do
    echo "Waiting for osm-bright..."
    sleep 5
done

eval "${@}"
