#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${__dir}"

until [[ -f "osm_bright.is_ready" ]]
do
    echo "Waiting for osm-bright..."
    sleep 5
done

eval "${@}"
