#!/bin/bash

set -e

MISSING_ENV_VAR_MSG="Environment variable needs to be set and non-empty."
: "${STATUS_VOLUME_PATH:?${MISSING_ENV_VAR_MSG}}"
: "${STYLES_VOLUME_PATH:?${MISSING_ENV_VAR_MSG}}"
: "${CONTENT_DIR_PATH:?${MISSING_ENV_VAR_MSG}}"

READYFILE="${STATUS_VOLUME_PATH}/osm_bright.is_ready"
OSM_BRIGHT_DIR="${STYLES_VOLUME_PATH}/OSMBright"
STYLEFILE="${OSM_BRIGHT_DIR}/OSMBright.xml"

if [[ ! -f "${STYLEFILE}" ]]
then
    rm -f "${READYFILE}"
fi

if [[ ! -f "${READYFILE}" ]]
then
    cd "${CONTENT_DIR_PATH}"

    wget "https://github.com/JanNash/osm-bright/archive/master.tar.gz"
    tar -xzf "osm-bright-master.tar.gz"
    rm "osm-bright-master.tar.gz"

    cp configure.py master/

    # This directory will be recreated by ./make.py
    # See configure.py for further reference
    rm -rf "${OSM_BRIGHT_DIR}"
    cd master
    ./make.py
    cd ..
    rm -rf master

    cd "${OSM_BRIGHT_DIR}"
    carto project.mml > OSMBright.xml

    touch "${READYFILE}"
fi
